"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.USER_TOKEN_IS_REQUIRED = exports.NO_WORKSPACE_FOUND_IN_CACHE = exports.WORKSPACE_NOT_FOUND = exports.WORKSPACE_NOT_ACTIVE = exports.WORKSPACE_IS_REQUIRED = exports.EMAIL_IS_REQUIRED = exports.PLUGIN_NOT_ACTIVE = exports.NO_PLUGIN_DATA_FOUND = exports.PLUGIN_ID_IS_REQUIRED = exports.TRANSACTIONS_NOT_FOUND = exports.TRANSACTION_NOT_FOUND = exports.TRANSACTION_ID_IS_REQUIRED = exports.INSUFICIENT_BALANCE = exports.AMOUNT_MUST_BE_GREATER_THAN_0 = exports.BALANCE_MUST_BE_A_NUMBER = exports.AMOUNT_MUST_BE_A_NUMBER = exports.LOYALTY_CARD_NOT_ACTIVE = exports.TYPE_MUST_BE_CREDIT_OR_DEBIT = exports.AMOUNT_GRATER_THAN_0 = exports.TYPE_IS_REQUIRED = exports.AMOUNT_IS_REQUIRED = exports.INVALID_PHONE_NUMBER = exports.NO_RESPONSE_FOUND = exports.UNAUTHORIZED = exports.ACCOUNT_IS_REQUIRED = exports.LOYALTY_CARD_ID_IS_REQUIRED = exports.LOYALTY_CARD_NOT_FOUND = exports.LOYALTY_CARD_NOT_CREATED = exports.INVALID_EMAIL = exports.API_KEY_IS_REQUIRED = exports.NO_ACCOUNT_FOUND_IN_CACHE = exports.ACCOUNT_NOT_FOUND = exports.MULTIPLE_ACCOUNTS_FOUND = exports.ACCOUNT_NOT_ACTIVE = void 0;
// Error messages
exports.ACCOUNT_NOT_ACTIVE = JSON.stringify({ message: 'Account not active', status: 402 });
exports.MULTIPLE_ACCOUNTS_FOUND = JSON.stringify({ message: 'Multiple accounts found', status: 500 });
exports.ACCOUNT_NOT_FOUND = JSON.stringify({ message: 'Account not found', status: 500 });
exports.NO_ACCOUNT_FOUND_IN_CACHE = JSON.stringify({ message: 'No account found in cache, fetching...' });
exports.API_KEY_IS_REQUIRED = JSON.stringify({ message: 'API key is required', status: 400 });
exports.INVALID_EMAIL = JSON.stringify({ message: 'Invalid email', status: 400 });
exports.LOYALTY_CARD_NOT_CREATED = JSON.stringify({ message: 'Loyalty Card not created', status: 500 });
exports.LOYALTY_CARD_NOT_FOUND = JSON.stringify({ message: 'Loyalty Card not found', status: 500 });
exports.LOYALTY_CARD_ID_IS_REQUIRED = JSON.stringify({ message: 'Loyalty Card ID is required', status: 400 });
exports.ACCOUNT_IS_REQUIRED = JSON.stringify({ message: 'Account is required', status: 400 });
exports.UNAUTHORIZED = JSON.stringify({ message: 'Unauthorized', status: 401 });
exports.NO_RESPONSE_FOUND = JSON.stringify({ message: 'Oops, something exploded!', status: 500 });
exports.INVALID_PHONE_NUMBER = JSON.stringify({ message: 'Invalid phone number', status: 400 });
exports.AMOUNT_IS_REQUIRED = JSON.stringify({ message: 'Amount is required', status: 400 });
exports.TYPE_IS_REQUIRED = JSON.stringify({ message: 'Type is required', status: 400 });
exports.AMOUNT_GRATER_THAN_0 = JSON.stringify({ message: 'Amount must be greater than 0', status: 400 });
exports.TYPE_MUST_BE_CREDIT_OR_DEBIT = JSON.stringify({ message: 'Type must be CREDIT or DEBIT', status: 400 });
exports.LOYALTY_CARD_NOT_ACTIVE = JSON.stringify({ message: 'Loyalty Card not active', status: 500 });
exports.AMOUNT_MUST_BE_A_NUMBER = JSON.stringify({ message: 'Amount must be a number', status: 400 });
exports.BALANCE_MUST_BE_A_NUMBER = JSON.stringify({ message: 'Balance must be a number', status: 500 });
exports.AMOUNT_MUST_BE_GREATER_THAN_0 = JSON.stringify({ message: 'Amount must be greater than 0', status: 400 });
exports.INSUFICIENT_BALANCE = JSON.stringify({ message: 'Insufficient balance', status: 500 });
exports.TRANSACTION_ID_IS_REQUIRED = JSON.stringify({ message: 'Transaction ID is required', status: 400 });
exports.TRANSACTION_NOT_FOUND = JSON.stringify({ message: 'Transaction not found', status: 500 });
exports.TRANSACTIONS_NOT_FOUND = JSON.stringify({ message: 'Transactions not found', status: 500 });
exports.PLUGIN_ID_IS_REQUIRED = JSON.stringify({ message: 'Plugin ID is required', status: 500 });
exports.NO_PLUGIN_DATA_FOUND = JSON.stringify({ message: 'No plugin data found', status: 500 });
exports.PLUGIN_NOT_ACTIVE = JSON.stringify({ message: 'Plugin not active', status: 500 });
exports.EMAIL_IS_REQUIRED = JSON.stringify({ message: 'Email is required', status: 400 });
exports.WORKSPACE_IS_REQUIRED = JSON.stringify({ message: 'Workspace is required', status: 400 });
exports.WORKSPACE_NOT_ACTIVE = JSON.stringify({ message: 'Workspace not active', status: 402 });
exports.WORKSPACE_NOT_FOUND = JSON.stringify({ message: 'Workspace not found', status: 500 });
exports.NO_WORKSPACE_FOUND_IN_CACHE = JSON.stringify({ message: 'No workspace found in cache, fetching...' });
exports.USER_TOKEN_IS_REQUIRED = JSON.stringify({ message: 'User token is required', status: 400 });
//# sourceMappingURL=errors.msg.js.map