"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.APIKEY_ALREADY_EXISTS = exports.MISSING_API_KEY = exports.BALANCE_MUST_BE_A_NUMBER = exports.LOYALTY_CARD_NOT_ACTIVE = exports.AMOUNT_GRATER_THAN_0 = exports.AMOUNT_MUST_BE_A_NUMBER = exports.LOYALTY_CARD_NOT_FOUND = exports.UNAUTHORIZED = exports.TYPE_MUST_BE_CREDIT_OR_DEBIT = exports.TYPE_IS_REQUIRED = exports.TRANSACTION_NOT_FOUND = exports.TRANSACTION_ID_IS_REQUIRED = exports.TRANSACTIONS_NOT_FOUND = exports.NO_RESPONSE_FOUND = exports.NO_ACCOUNT_FOUND_IN_CACHE = exports.MULTIPLE_ACCOUNTS_FOUND = exports.LOYALTY_CARD_NOT_CREATED = exports.LOYALTY_CARD_ID_IS_REQUIRED = exports.INVALID_PHONE_NUMBER = exports.INVALID_EMAIL = exports.INSUFICIENT_BALANCE = exports.API_KEY_IS_REQUIRED = exports.AMOUNT_MUST_BE_GREATER_THAN_0 = exports.AMOUNT_IS_REQUIRED = exports.ACCOUNT_NOT_FOUND = exports.ACCOUNT_NOT_ACTIVE = exports.ACCOUNT_IS_REQUIRED = exports.NO_PLUGIN_DATA_FOUND = exports.PLUGIN_NOT_ACTIVE = exports.PLUGIN_ID_IS_REQUIRED = exports.WORKSPACE_NOT_FOUND = exports.WORKSPACE_NOT_ACTIVE = exports.WORKSPACE_IS_REQUIRED = exports.USER_TOKEN_IS_REQUIRED = exports.NO_WORKSPACE_FOUND_IN_CACHE = exports.EMAIL_IS_REQUIRED = exports.TOKEN_IS_NOT_VALID = exports.API_KEY_NAME_IS_REQUIRED = exports.APIKEY_DO_NOT_EXISTS = exports.removeChars = exports.removeSpecialChars = exports.validatePhoneNumber = exports.validateEmail = exports.sanitizeJson = exports.validateWorkspace = exports.response = exports.errorHandler = exports.logErrors = exports.validatePlugin = exports.validateAccount = void 0;
exports.WORKSPACES = exports.TRANSACTIONS = exports.LOYALTY_CARDS = exports.ACCOUNTS = exports.ACCOUNT = exports.FIVE_MIN = exports.EQUALS = exports.ARRAY_CONTAINS = exports.ACCOUNT_IN_MEMORY = exports.YEAR = exports.STYRK_LOYALTY = exports.VTEX = exports.USER_ID = exports.USER = exports.PHONE = exports.NUMBER = exports.ID = exports.GID = exports.EMAIL = exports.DESC = exports.ASC = exports.HEX = exports.API_KEY = void 0;
// Middlewares
const validateAccount_mdw_1 = __importDefault(require("./src/middlewares/account/validateAccount.mdw"));
exports.validateAccount = validateAccount_mdw_1.default;
const logErrors_mdw_1 = __importDefault(require("./src/middlewares/error/logErrors.mdw"));
exports.logErrors = logErrors_mdw_1.default;
const errorHandler_mdw_1 = __importDefault(require("./src/middlewares/error/errorHandler.mdw"));
exports.errorHandler = errorHandler_mdw_1.default;
const response_mdw_1 = __importDefault(require("./src/middlewares/response.mdw"));
exports.response = response_mdw_1.default;
const validatePlugin_mdw_1 = __importDefault(require("./src/middlewares/account/validatePlugin.mdw"));
exports.validatePlugin = validatePlugin_mdw_1.default;
const validateWorkspace_1 = __importDefault(require("./src/middlewares/workspaces/validateWorkspace"));
exports.validateWorkspace = validateWorkspace_1.default;
// Utils
const sanitizeJson_1 = __importDefault(require("./src/utils/sanitizeJson"));
exports.sanitizeJson = sanitizeJson_1.default;
const validateEmail_1 = __importDefault(require("./src/utils/validateEmail"));
exports.validateEmail = validateEmail_1.default;
const validatePhoneNumber_1 = __importDefault(require("./src/utils/validatePhoneNumber"));
exports.validatePhoneNumber = validatePhoneNumber_1.default;
const removeSpecialChars_1 = __importDefault(require("./src/utils/removeSpecialChars"));
exports.removeSpecialChars = removeSpecialChars_1.default;
const removeChars_1 = __importDefault(require("./src/utils/removeChars"));
exports.removeChars = removeChars_1.default;
// Constants
var errors_msg_1 = require("./src/constants/errors.msg");
Object.defineProperty(exports, "APIKEY_DO_NOT_EXISTS", { enumerable: true, get: function () { return errors_msg_1.APIKEY_DO_NOT_EXISTS; } });
Object.defineProperty(exports, "API_KEY_NAME_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.API_KEY_NAME_IS_REQUIRED; } });
Object.defineProperty(exports, "TOKEN_IS_NOT_VALID", { enumerable: true, get: function () { return errors_msg_1.TOKEN_IS_NOT_VALID; } });
Object.defineProperty(exports, "EMAIL_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.EMAIL_IS_REQUIRED; } });
Object.defineProperty(exports, "NO_WORKSPACE_FOUND_IN_CACHE", { enumerable: true, get: function () { return errors_msg_1.NO_WORKSPACE_FOUND_IN_CACHE; } });
Object.defineProperty(exports, "USER_TOKEN_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.USER_TOKEN_IS_REQUIRED; } });
Object.defineProperty(exports, "WORKSPACE_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.WORKSPACE_IS_REQUIRED; } });
Object.defineProperty(exports, "WORKSPACE_NOT_ACTIVE", { enumerable: true, get: function () { return errors_msg_1.WORKSPACE_NOT_ACTIVE; } });
Object.defineProperty(exports, "WORKSPACE_NOT_FOUND", { enumerable: true, get: function () { return errors_msg_1.WORKSPACE_NOT_FOUND; } });
Object.defineProperty(exports, "PLUGIN_ID_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.PLUGIN_ID_IS_REQUIRED; } });
Object.defineProperty(exports, "PLUGIN_NOT_ACTIVE", { enumerable: true, get: function () { return errors_msg_1.PLUGIN_NOT_ACTIVE; } });
Object.defineProperty(exports, "NO_PLUGIN_DATA_FOUND", { enumerable: true, get: function () { return errors_msg_1.NO_PLUGIN_DATA_FOUND; } });
Object.defineProperty(exports, "ACCOUNT_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.ACCOUNT_IS_REQUIRED; } });
Object.defineProperty(exports, "ACCOUNT_NOT_ACTIVE", { enumerable: true, get: function () { return errors_msg_1.ACCOUNT_NOT_ACTIVE; } });
Object.defineProperty(exports, "ACCOUNT_NOT_FOUND", { enumerable: true, get: function () { return errors_msg_1.ACCOUNT_NOT_FOUND; } });
Object.defineProperty(exports, "AMOUNT_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.AMOUNT_IS_REQUIRED; } });
Object.defineProperty(exports, "AMOUNT_MUST_BE_GREATER_THAN_0", { enumerable: true, get: function () { return errors_msg_1.AMOUNT_MUST_BE_GREATER_THAN_0; } });
Object.defineProperty(exports, "API_KEY_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.API_KEY_IS_REQUIRED; } });
Object.defineProperty(exports, "INSUFICIENT_BALANCE", { enumerable: true, get: function () { return errors_msg_1.INSUFICIENT_BALANCE; } });
Object.defineProperty(exports, "INVALID_EMAIL", { enumerable: true, get: function () { return errors_msg_1.INVALID_EMAIL; } });
Object.defineProperty(exports, "INVALID_PHONE_NUMBER", { enumerable: true, get: function () { return errors_msg_1.INVALID_PHONE_NUMBER; } });
Object.defineProperty(exports, "LOYALTY_CARD_ID_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.LOYALTY_CARD_ID_IS_REQUIRED; } });
Object.defineProperty(exports, "LOYALTY_CARD_NOT_CREATED", { enumerable: true, get: function () { return errors_msg_1.LOYALTY_CARD_NOT_CREATED; } });
Object.defineProperty(exports, "MULTIPLE_ACCOUNTS_FOUND", { enumerable: true, get: function () { return errors_msg_1.MULTIPLE_ACCOUNTS_FOUND; } });
Object.defineProperty(exports, "NO_ACCOUNT_FOUND_IN_CACHE", { enumerable: true, get: function () { return errors_msg_1.NO_ACCOUNT_FOUND_IN_CACHE; } });
Object.defineProperty(exports, "NO_RESPONSE_FOUND", { enumerable: true, get: function () { return errors_msg_1.NO_RESPONSE_FOUND; } });
Object.defineProperty(exports, "TRANSACTIONS_NOT_FOUND", { enumerable: true, get: function () { return errors_msg_1.TRANSACTIONS_NOT_FOUND; } });
Object.defineProperty(exports, "TRANSACTION_ID_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.TRANSACTION_ID_IS_REQUIRED; } });
Object.defineProperty(exports, "TRANSACTION_NOT_FOUND", { enumerable: true, get: function () { return errors_msg_1.TRANSACTION_NOT_FOUND; } });
Object.defineProperty(exports, "TYPE_IS_REQUIRED", { enumerable: true, get: function () { return errors_msg_1.TYPE_IS_REQUIRED; } });
Object.defineProperty(exports, "TYPE_MUST_BE_CREDIT_OR_DEBIT", { enumerable: true, get: function () { return errors_msg_1.TYPE_MUST_BE_CREDIT_OR_DEBIT; } });
Object.defineProperty(exports, "UNAUTHORIZED", { enumerable: true, get: function () { return errors_msg_1.UNAUTHORIZED; } });
Object.defineProperty(exports, "LOYALTY_CARD_NOT_FOUND", { enumerable: true, get: function () { return errors_msg_1.LOYALTY_CARD_NOT_FOUND; } });
Object.defineProperty(exports, "AMOUNT_MUST_BE_A_NUMBER", { enumerable: true, get: function () { return errors_msg_1.AMOUNT_MUST_BE_A_NUMBER; } });
Object.defineProperty(exports, "AMOUNT_GRATER_THAN_0", { enumerable: true, get: function () { return errors_msg_1.AMOUNT_GRATER_THAN_0; } });
Object.defineProperty(exports, "LOYALTY_CARD_NOT_ACTIVE", { enumerable: true, get: function () { return errors_msg_1.LOYALTY_CARD_NOT_ACTIVE; } });
Object.defineProperty(exports, "BALANCE_MUST_BE_A_NUMBER", { enumerable: true, get: function () { return errors_msg_1.BALANCE_MUST_BE_A_NUMBER; } });
Object.defineProperty(exports, "MISSING_API_KEY", { enumerable: true, get: function () { return errors_msg_1.MISSING_API_KEY; } });
Object.defineProperty(exports, "APIKEY_ALREADY_EXISTS", { enumerable: true, get: function () { return errors_msg_1.APIKEY_ALREADY_EXISTS; } });
var headers_msg_1 = require("./src/constants/headers.msg");
Object.defineProperty(exports, "API_KEY", { enumerable: true, get: function () { return headers_msg_1.API_KEY; } });
var keys_msg_1 = require("./src/constants/keys.msg");
Object.defineProperty(exports, "HEX", { enumerable: true, get: function () { return keys_msg_1.HEX; } });
Object.defineProperty(exports, "ASC", { enumerable: true, get: function () { return keys_msg_1.ASC; } });
Object.defineProperty(exports, "DESC", { enumerable: true, get: function () { return keys_msg_1.DESC; } });
Object.defineProperty(exports, "EMAIL", { enumerable: true, get: function () { return keys_msg_1.EMAIL; } });
Object.defineProperty(exports, "GID", { enumerable: true, get: function () { return keys_msg_1.GID; } });
Object.defineProperty(exports, "ID", { enumerable: true, get: function () { return keys_msg_1.ID; } });
Object.defineProperty(exports, "NUMBER", { enumerable: true, get: function () { return keys_msg_1.NUMBER; } });
Object.defineProperty(exports, "PHONE", { enumerable: true, get: function () { return keys_msg_1.PHONE; } });
Object.defineProperty(exports, "USER", { enumerable: true, get: function () { return keys_msg_1.USER; } });
Object.defineProperty(exports, "USER_ID", { enumerable: true, get: function () { return keys_msg_1.USER_ID; } });
Object.defineProperty(exports, "VTEX", { enumerable: true, get: function () { return keys_msg_1.VTEX; } });
Object.defineProperty(exports, "STYRK_LOYALTY", { enumerable: true, get: function () { return keys_msg_1.STYRK_LOYALTY; } });
Object.defineProperty(exports, "YEAR", { enumerable: true, get: function () { return keys_msg_1.YEAR; } });
var messages_msg_1 = require("./src/constants/messages.msg");
Object.defineProperty(exports, "ACCOUNT_IN_MEMORY", { enumerable: true, get: function () { return messages_msg_1.ACCOUNT_IN_MEMORY; } });
var operations_msg_1 = require("./src/constants/operations.msg");
Object.defineProperty(exports, "ARRAY_CONTAINS", { enumerable: true, get: function () { return operations_msg_1.ARRAY_CONTAINS; } });
Object.defineProperty(exports, "EQUALS", { enumerable: true, get: function () { return operations_msg_1.EQUALS; } });
Object.defineProperty(exports, "FIVE_MIN", { enumerable: true, get: function () { return operations_msg_1.FIVE_MIN; } });
var routes_msg_1 = require("./src/constants/routes.msg");
Object.defineProperty(exports, "ACCOUNT", { enumerable: true, get: function () { return routes_msg_1.ACCOUNT; } });
Object.defineProperty(exports, "ACCOUNTS", { enumerable: true, get: function () { return routes_msg_1.ACCOUNTS; } });
Object.defineProperty(exports, "LOYALTY_CARDS", { enumerable: true, get: function () { return routes_msg_1.LOYALTY_CARDS; } });
Object.defineProperty(exports, "TRANSACTIONS", { enumerable: true, get: function () { return routes_msg_1.TRANSACTIONS; } });
Object.defineProperty(exports, "WORKSPACES", { enumerable: true, get: function () { return routes_msg_1.WORKSPACES; } });
//# sourceMappingURL=index.js.map